[package]
name = "ls"
version = "0.1.0"
authors = ["Lucas Leonardo <lucasleonardo@protonmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
clap = { version = "^2.33.0", features = ["yaml", "wrap_help"] }

[build-dependencies]
clap = { version = "^2.33.0", features = ["yaml"] }
