status = [
    "Linux (1.61.0)",
    "Linux (stable)",
    "MacOS (1.61.0)",
    "MacOS (stable)",
    "FreeBSD (1.61.0)",
    "FreeBSD (stable)",
    "NetBSD (1.61.0)",
    "NetBSD (stable)",
    "Illumos (1.61.0)",
    "Illumos (stable)",
    "Fuchsia (1.61.0)",
    "Fuchsia (stable)",
    "OpenBSD (nightly)",
    # "Solaris (nightly)",
    # "DragonflyBSD (nightly)",
    # "Haiku (nightly)",
    "Format",
]
commit_title = "chore: Merge ${PR_REFS}"
delete_merged_branches = true
