status = [
    "Linux (1.58.0)",
    "Linux (stable)",
    "MacOS (1.58.0)",
    "MacOS (stable)",
    "FreeBSD (1.58.0)",
    "FreeBSD (stable)",
    "NetBSD (1.58.0)",
    "NetBSD (stable)",
    "Illumos (1.58.0)",
    "Illumos (stable)",
    "Solaris (1.58.0)",
    "Solaris (stable)",
    "Fuchsia (1.58.0)",
    "Fuchsia (stable)",
    "DragonflyBSD (nightly)",
    "OpenBSD (nightly)",
    "Haiku (nightly)",
    "Format",
]
delete_merged_branches = true
