[package]
name = "wc"
version = "0.1.0"
authors = ["Giacomo Parolini <silverweed1991@gmail.com>"]
license = "MPL-2.0-no-copyleft-exception"
build = "build.rs"
edition = "2021"
rust-version = "1.56.1"
description = """
Display newline, word and byte counts for each FILE, and a total line if more than one FILE is \
specified. A word is a non-zero-length sequence of characters delimited by white space.

With no FILE, or when FILE is -, read standard input.
"""

[dependencies]
clap = { version = "^2.33.0", features = ["wrap_help"] }

[build-dependencies]
clap = "^2.33.0"
