name: Deny

on: [push, pull_request]

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v1