name: DragonflyBSD

on: [push, pull_request]

jobs:
  check:
    name: DragonflyBSD
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [nightly]
        # rust: [1.46.0, stable]
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: rust-src
    - name: Setup TOML
      run: cp DragonflyBSD.toml Cargo.toml
    - name: Check DragonflyBSD
      run: cargo check --target x86_64-unknown-dragonfly -Z build-std
