name: DragonflyBSD

on: [push]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [1.37.0, stable]
    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Install target
      run: rustup target add x86_64-unknown-dragonfly
    - name: Check DragonflyBSD
      run: |
        cp DragonflyBSD.toml Cargo.toml
        cargo check --verbose --target x86_64-unknown-dragonfly
