name: Format test

on: [push, pull_request]

jobs:
  build:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: rustfmt
    - name: Check Format
      run: cargo fmt -- --check
