name: Fuchsia

on: [push, pull_request]

jobs:
  check:
    name: Fuchsia
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.56.1, stable]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
        target: x86_64-fuchsia
    - name: Add more targets
      run: rustup target add aarch64-fuchsia
    - name: Setup TOML
      run: cp Fuchsia.toml Cargo.toml
    - name: Check Fuchsia (x86_64)
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --target x86_64-fuchsia
    - name: Check Fuchsia (aarch64)
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --target aarch64-fuchsia

