name: Fuchsia

on: [push, pull_request]

jobs:
  check:
    name: Fuchsia
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.58.0, stable]
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        target: x86_64-fuchsia
    - name: Setup TOML
      run: cp Fuchsia.toml Cargo.toml
    - name: Add more targets
      run: rustup target add aarch64-fuchsia
    - name: Check Fuchsia (x86_64)
      run: cargo check --target x86_64-fuchsia
    - name: Check Fuchsia (aarch64)
      run: cargo check --target aarch64-fuchsia

