name: Illumos

on: [push, pull_request]

jobs:
  build:
    name: Illumos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.61.0, stable]
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: clippy
        target: x86_64-unknown-illumos
    - name: Setup TOML
      run: cp Illumos.toml Cargo.toml
    - name: Check Illumos
      run: cargo check --target x86_64-unknown-illumos
