name: OpenBSD

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [1.37.0, stable]
    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Install target
      run: rustup target add x86_64-unknown-openbsd
    - name: Check OpenBSD --target x86_64-unknown-openbsd
      run: |
        cp OpenBSD.toml Cargo.toml
        cargo check --verbose
