name: OpenBSD

on: [push, pull_request]

jobs:
  build:
    name: OpenBSD
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # rust: [1.46.0, stable]
        rust: [nightly]
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: rust-src
    - name: Check OpenBSD
      run: cargo check --target x86_64-unknown-openbsd --manifest-path ./OpenBSD.toml -Z build-std
